# Generated by Django 4.2.6 on 2024-02-28 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('cooking_steps', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.PositiveIntegerField(default=0, verbose_name='Время приготовления')),
                ('img', models.ImageField(blank=True, null=True, upload_to='recipe', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение')),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Калорийность')),
                ('portions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество порций')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('category', models.ManyToManyField(to='mainapp.category')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.recipe')),
            ],
        ),
    ]
